apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-ui
  namespace: retail-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retail-ui
  template:
    metadata:
      labels:
        app: retail-ui
    spec:
      containers:
      - name: ui
        image: public.ecr.aws/aws-containers/retail-store-sample-ui:0.4.0
        ports:
        - containerPort: 8080
        env:
        - name: CATALOG_ENDPOINT
          value: "http://catalog:80"
---
apiVersion: v1
kind: Service
metadata:
  name: ui-service
  namespace: retail-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: retail-ui
