apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::864443358235:user/project-bedrock-developer
      username: project-bedrock-developer
      groups:
        - system:masters
